### ISSUE TITLE
Codificação RF 1.5 a 1.8

### ISSUE THREAD

**Issue by GuiBatalhoti** [Team-Dire/FCT_Estacionatron_3000#16]
Fazer a codificação dos RF 1.5 a 1.8.
Programador: @G-Nozawa.

**Comment by GuiBatalhoti** [comment]
Iniciado 16/12/2022 Finalizado 22/12/2022

**Comment by Salies** [comment]
1. O código utiliza-se da classe Date e de seus respectivos métodos, contudo já havia sido conversado nos demais canais da equipe que seria melhor o uso de Calendar, mesmo quando os artefatos de projeto indicarem Date.
2. O programa não permite reabertura do estacionamento após o fechamento, afirmando "o estacionamento já foi aberto".
3. O programa não recupera vagas após o pagamento. Como o pagamento é na saída, a vaga ocupada pelo veículo deveria ser "devolvida" às disponíveis no ato do pagamento.

**Comment by GuiBatalhoti** [comment]
Corrigido, mas não documentado anteriormente pelo programador.
